In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import sklearn.datasets 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
df=pd.read_csv('SMSSpamCollection',sep='\t',names=['Status','Message'])

In [4]:
df.head()

Status                                            Message
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
len(df)

5572

In [6]:
len(df[df.Status=='spam'])

747

In [7]:
df.loc[df['Status']=='ham',"Status"]=1
df.loc[df['Status']=='spam',"Status"]=0

In [8]:
df.head()

Status                                            Message
0      1  Go until jurong point, crazy.. Available only ...
1      1                      Ok lar... Joking wif u oni...
2      0  Free entry in 2 a wkly comp to win FA Cup fina...
3      1  U dun say so early hor... U c already then say...
4      1  Nah I don't think he goes to usf, he lives aro...

In [9]:
df_x=df['Message']
df_y=df['Status']

In [10]:
df_x

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [11]:
cv=CountVectorizer()

In [12]:
x_train, x_test, y_train, y_test=train_test_split(df_x,df_y,test_size=0.2,random_state=101)

In [13]:
x_traincv=cv.fit_transform(['Hi how are you, how are you doing?',"Hey what's up"])

In [14]:
x_traincv.toarray()

array([[2, 1, 0, 1, 2, 0, 0, 2],
       [0, 0, 1, 0, 0, 1, 1, 0]], dtype=int64)

In [15]:
cv.get_feature_names()

['are', 'doing', 'hey', 'hi', 'how', 'up', 'what', 'you']

In [16]:
cv1=CountVectorizer()

In [17]:
x_traincv=cv1.fit_transform(x_train)

In [18]:
a=x_traincv.toarray()

In [19]:
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [20]:
a[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [21]:
cv1.inverse_transform(a[0])

[array(['bad', 'feel', 'lar', 'lor', 'need', 'no', 'then', 'wait', 'we'],
       dtype='<U34')]

In [22]:
len(a[0])

7778

In [23]:
x_train.iloc[0]

'Then we wait 4 u lor... No need 2 feel bad lar...'

In [26]:
cv=TfidfVectorizer(min_df=1,stop_words='english')

In [29]:
x_train, x_test, y_train, y_test=train_test_split(df_x,df_y,test_size=0.2,random_state=101)

In [30]:
x_traincv=cv.fit_transform(['Hi how are you, how are you doing?',"Hey what's up"])

In [31]:
x_traincv.toarray()

array([[0.70710678, 0.        , 0.70710678],
       [0.        , 1.        , 0.        ]])

In [32]:
cv.get_feature_names()

['doing', 'hey', 'hi']

In [33]:
cv1=TfidfVectorizer(min_df=1,stop_words='english')

In [34]:
x_traincv=cv1.fit_transform(x_train)

In [36]:
a=x_traincv.toarray()

In [37]:
a

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [38]:
a[0
 ]

array([0., 0., 0., ..., 0., 0., 0.])

In [39]:
cv1.inverse_transform(a[0])

[array(['bad', 'feel', 'lar', 'lor', 'need', 'wait'], dtype='<U34')]

In [40]:
len(a[0])

7511

In [41]:
x_train.iloc[0]

'Then we wait 4 u lor... No need 2 feel bad lar...'

In [42]:
# Machine Learning Algorithm

In [43]:
mnb=MultinomialNB()

In [44]:
y_train=y_train.astype('int')

In [45]:
mnb.fit(x_traincv,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [47]:
x_testcv=cv1.transform(x_test)

In [48]:
pred=mnb.predict(x_testcv)

In [49]:
pred

array([1, 0, 1, ..., 1, 1, 1])

In [50]:
actual=np.array(y_test)

In [51]:
actual

array([1, 0, 0, ..., 1, 1, 1], dtype=object)

In [53]:
count=0
for i in range(len(pred)):
    if pred[i]==actual[i]:
        count=count+1

In [54]:
count

1079

In [55]:
len(pred)

1115

In [56]:
1079/1115

0.967713004484305